### ISSUE TITLE
Assessment 3

### ISSUE THREAD

**Issue by rizzamandasari** [Alifalfaidz/Assesment_3_Mobpro#1]
Aplikasi dapat berjalan, aplikasi pun menunjang user untuk melakukan login namun
1. Proses input tidak dapat berjalan.
2. Gender jika memang sudah ditentukan (P, L, Unisex) maka dapat menggunakan select atau radio button
3. Sehingga fitur delete, logout dan loading indicator tidak dapat dicek.
Perbaikan dapat di submit sebelum 25 Juni 2024

**Comment by Alifalfaidz** [comment]
mohon maaf ibu setelah saya check lagi, karena saya memakai api generator ada batasan maksimum string, karena gambarnya saya ubah jadi string. sehingga  input datanya jadi gagal ibu.

**Comment by rizzamandasari** [comment]
oke close ya lif
